import { Roboto } from "next/font/google";
import "./globals.css";
import { ClerkProvider } from "@clerk/nextjs";
import Provider from "./Provider";

const roboto = Roboto({
  weight:['300','400','500','700'],
  variable: "--font-roboto",
  subsets: ["latin"],
});

export const metadata = {
  title: "Story Kids | AI Content Generator",
  description: "Generated by create next app",
};

export default function RootLayout({ children }) {
  return (
    <ClerkProvider>
        <html lang="en">
          <body className={`${roboto.variable} antialiased`}>
            <Provider>
              {children}
            </Provider>
          </body>
        </html>
    </ClerkProvider>
  );
}
